### ISSUE TITLE
rock not working on 3.7 with fabio 0.7.0

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/fabian#11]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/jon/.local/lib/python3.7/site-packages/Fabian/appWin.py", line 791, in GoRock
    rockdata.run()
  File "/home/jon/.local/lib/python3.7/site-packages/Fabian/rocker.py", line 43, in run
    next(series)
TypeError: 'image_file_series' object is not an iterator
```

**Comment by jonwright** [comment]
Fixed by #18
